
name: ridesharing
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.1
  cached_network_image: ^3.2.0
  share_plus: ^12.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.0.13
  intl: ^0.18.1  # AJOUTÉ pour le formatage des dates

  # Base de données SQLite
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/
    - assets/images/cars/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
  